livepeer/livepeer-data

- api/authorization.go
- api/handler.go
- api/regionProxy.go
- api/streamStatus.go
- api/util.go
- cmd/analyzer/analyzer.go
- docker-compose.yml
- go.mod
- go.sum
- health/core.go
- health/record.go
- health/reducers/media_server_metrics.go
- health/reducers/transcode.go
This is to implement authorization to the stream health APis by leveraging from the new API created
in livepeer-com: https://github.com/livepeer/livepeer-com/pull/682
The main logical change here was that I introduced this new simples midldewares library for the
API handler (hitch). It's very minimal to the point that I just read its whole code and it looks just like
what I thought of implemented myself, so we might as well delegate it (and go.sum will save us from
any bad updates anyway).
Also included a few other changes in here like adding a little more logs around the code, since I've
started feeling that `analyzer` is currently very black-box-y when it's running in production. So this
will improve that a bit.
This implements https://github.com/livepeer/livepeer-data/issues/4.
> analyzer: Implement authorization on APIs

- health/record.go
- health/reducers/stream_state.go
- health/types.go
We currently carry-over state from previous sessions to the next, which makes a lot of
stuff in the dashboard display weirdly when we start a new stream. i.e. the API response
payloads are weird cause they keep information about previous sessions.
This fixes that by actually clearing the stream state when we process an event about a stream
becoming active. 
The right long-term approach would be to index these heath status by session ID instead so
we don't mix them together, but IMO this is the best approach for now, since indexing by session ID
would require adding that context to every place we currently send events from, including for
example `mist-api-connector`. So we can keep that one for sometime later.
> analyzer: Fix handling of stream status when a new session starts

- api/regionProxy.go
We were responding with multiple CORS headers which is invalid.
I thought about just moving the middlewares order as well, but that would imply that 404 responses
coming from the `streamStatus` would not get the CORS headers and then weird errors as well.
I think this fix makes conceptual sense as well, so I'm ok with it, but lmk of any other ideas that might
work out better. The other entrypoint we would have is `ReverseProxy`'s `ModifyResponse`, but didn't
think that was very good either.
> analyzer: Fix CORS when region-proxying a request

- api/errors.go
- api/streamStatus.go
- cmd/analyzer/analyzer.go
- health/core.go
- health/record.go
- health/reducer.go
- health/reducers/health.go
- health/reducers/media_server_metrics.go
- health/reducers/multistream.go
- health/reducers/pipeline.go
- health/reducers/stats.go
- health/reducers/stream_state.go
- health/reducers/transcode.go
- pkg/client/analyzer.go
- pkg/client/apiError.go
- pkg/data/healthStatus.go
This is to create a public package with an HTTP client for the Stream Health analyzer API.
To be used by `stream-tester` for testing Stream Health availability.
Only including `/health` API initially which is the minimum we need. 
SSE will either need adding a third-party library or writing some custom parsing logic, so
will leave it for when we really need it. Would be really awesome to POC that idea of
implementing the same reducer logic in the client code though.
> pkg/client: Create client for analyzer API

- cmd/analyzer/analyzer.go
- pkg/mist-connector/main.go
- pkg/mistconnector/main.go
Related to #35.
This would allow the built binary to be added as a mist capability.
The flag generates output as the following (click "Details" to expand):
<details>
```
{
"name": "LivepeerAnalyzer",
"desc": "Stream health data analyzer service for aggregated reporting of running streams status",
"friendly": "Livepeer Analyzer",
"optional": {
"amqp-uri": {
"name": "amqp-uri",
"help": "Explicit AMQP URI in case of non-default protocols/ports (optional). Must point to the same cluster as rabbitmqUri",
"option": "-amqp-uri"
},
"api-root": {
"name": "api-root",
"help": "Root path where to bind the API to",
"option": "-api-root",
"default": "/data",
"type": "str"
},
"auth-url": {
"name": "auth-url",
"help": "Endpoint for an auth server to call for both authentication and authorization of API …
```
> Add support for mist runtime to identify binaries.

- pkg/mistconnector/main.go
A default value of `0` for a flag validates the boolean flag check for
integer type fields. The boolean check will now occur only if integer
check fails.
> pkg/mistconnector: Fix issue with `0` being treated as boolean type.

- pkg/event/amqp_client.go
- pkg/event/amqp_conn.go
- pkg/event/amqp_consumer.go
- pkg/event/amqp_producer.go
- pkg/event/interfaces.go
- pkg/event/simple_producers.go
This will be needed by mist-api-connector for consuming messages from RabbitMQ.
Specifically, for the `CLIP_CREATED` events from the API which should be used for actually creating
the clips from the mist buffer locally (restreaming to broadcaster and etc).
> pkg/event: Create AMQP consumer client

- cmd/analyzer/analyzer.go
- health/core.go
- pkg/event/interfaces.go
This is to improve reliability of the analyzer, by detecting if we get no messages from RabbitMQ
and starting to respond with an error on the service healthcheck. This is because we've noticed that 
the RabbitMQ stream consumer lib fails to detect when RabbitMQ clusters are disconnected and
just stays there for a long time without receiving any messages until we manually restart the analyzers.
This is very similar to #49 but with a much simpler logic. Instead of attempting to heal the client internally,
we'll just start responding with an error on the healthcheck and let Kubernetes restart the container
through a liveness probe.
> analyzer: Fail healtcheck after some time without messages

- api/authorization.go
- api/errors.go
- api/handler.go
- api/streamStatus.go
- views/client.go
This is to add proper authorization to the viewership API. Meaning we do the same scheme as for 
stream health on the `/views` API.
This means calling the Studio API with the `Authorization` header for it to authorize the given request.
We also need to provide the ID of the asset being accessed, since Studio API shouldn't handle parsing
our own API paths (although it will contain our API format to allow CORS on it).
Either way, the other relevant change is that now you can't call the playback API with the asset playback ID.
Need to use the ID instead. This was to simplify the whole authorization logic. Since this API is authenticated
now, I believe this is fine.
We will need to rethink it when we want an actually public API tho, since only the playback ID may be available
in that context. …
> api: Add authorization to viewership API

- .github/dependabot.yaml
- .github/workflows/build.yaml
- go.mod
Built binaries, are uploaded to gcp bucket for each commit. Additionally, merge multiple build jobs into a single one.
Part of work wrt: https://github.com/livepeer/livepeer-infra/issues/917
---
example manifest data:
```json
{
"branch": "hjp/gcp-upload",
"builds": {
"darwin-amd64": "https://build.livepeer.live/livepeer-data/6e2cc7ab1cb332accdd7ee4088251f90a5e0db7e/livepeer-analyzer-darwin-amd64.tar.gz",
"darwin-arm64": "https://build.livepeer.live/livepeer-data/6e2cc7ab1cb332accdd7ee4088251f90a5e0db7e/livepeer-analyzer-darwin-arm64.tar.gz",
"linux-amd64": "https://build.livepeer.live/livepeer-data/6e2cc7ab1cb332accdd7ee4088251f90a5e0db7e/livepeer-analyzer-linux-amd64.tar.gz",
"linux-arm64": "https://build.livepeer.live/livepeer-data/6e2cc7ab1cb332accdd7ee4088251f90a5e0db7e/livepeer-analyz …
```
> build.yaml: Add GCP upload job to workflow

- pkg/event/amqp_consumer.go
This is to improve reliability of the AMQP consumer after a few limitations noticed 
on the latest incident we had with `task-runner` panics.
Main changes:
- Main fix: Recover from handler panics separately from panics in the consumer itself, and nack them [1]. A panic in the handler should not close the whole consumer.
- Check when the subscription channel is closed and don't send an empty event to handlers
- Try nacking the message when the ack fails (just to be extra safe. but the nack will likely also fail)
- Make sure to drain the subscription channel on exit to avoid blocking the AMQP connection (as stated in the docs)
- Created a special error type to be returned by consumer to indicate that the message should not be requeued
- Made sure not to requeue panicked messages either
LFG …
> pkg/event: Improve reliability of AMQP consumer

- pkg/data/task_result.go
Add output to the transcode-file task.
In the case of web3storage, we need it to return the output video URL to the end user.
> Add TranscodeFileTaskOutput

- views/bigquery.go
They better be compatible to the fields
that we return on the response objects.
Those should be camelCase as its the pattern
in the current API, so made the breakdownBy
fields camelCase as well.
I was really confused with the API myself when writing
a code to breakdown by device_type then gets a deviceType
in the response 0o
> views: Fix the query string breakdown casing

- api/handler.go
- views/bigquery.go
- views/client.go
I found out after the initial version that the viewership summary and viewership
events tables don't actually have the same data: the summary one has the 
prometheus data backward compatibility while the events one does not.
To make that distinction clearer to the end-user, added a new metric on the
summary query responses called `legacyViewCount`, which contains the
number of views that have been migrated from the prometheus data and 
thus will not show up in the detailed query endpoints.
Also removed a refactor that did a cheaper summary query when the 
events query was made with just a playback ID. This is not possible anymore,
since the tables contain different data, so we cannot replace one query with 
the other. 
The coded ended up a little simpler tho, without magic attempt to …
> api/views: Better separate summary from events queries

- api/handler.go
After #129 I fixed the general OPTIONS handling, but there was 1 corner case
that I missed: we have a `streamStatus` middleware that tries to fetch the stream
healthy before we do any authorization. This meant that OPTIONS requests for
inexistent streams were getting a 404 error, even though it should be a 204 and
the 404 only come to the actual GET request.
This is a less critical issue, but still a confusing experince. So I moved the authorization
middleware to be the first one so it handles OPTIONS before anyone. I've also verified
that there were no dependencies between it and the region proxy / stream status middlewares,
I think it was only left to the end before to avoid authorizing twice in the case of cross-region
proxy. This is not a big issue though, so deal with the double …
> api/handler: Move authorization before streamStatus

- pkg/data/parse.go
- pkg/data/task_partial_result.go
We'll use this to notify from task-runner to studio about the availability of source playback
> Introduce new event type for source playback

- api/streamStatus.go
- cmd/analyzer/analyzer.go
- docker-compose.yml
Some VPNs are messing up with the RabbitMQ connection so let's allow running without it.
> analyzer: Fixes for running analyzer in diverse local environments

- cmd/analyzer/analyzer.go
- health/core.go
We were accidentally closing the consumer as soon as it was created since we 
move its initialization to a helper function. Fix it by making the healthcore expose 
a Close function instead that is deferred-called by the main function instead.
> cmd/analyzer: Fix healthcore initialization

- health/reducers/media_server_metrics.go
Some events are coming without stats apparently. Don't really know why but the reducer should be resilient to that.
> reducers: Fix NRE in media server metrics

- health/core.go
- health/reducers/media_server_metrics.go
- pkg/event/stream_consumer.go
This fixes another NRE found on the media server metrics code, which for some reason are getting some nil values sometimes.
Since we've been getting some of these frequently I also made some improvemenets to the panic handling code:
- On the "rabbitmq stream consumer", include the message data in the panic log
- On the "health core", recover from panics in reducers and skip the event instead of restarting the app
> health: Fix yet another NRE and improve panic handling

- api/handler.go
- cmd/analyzer/analyzer.go
- usage/bigquery.go
- usage/client.go
This removes any need to fetch users by activity on studio and doing multiple api calls to data to retrieve usage for these users. In a single api, you can fetch usage for active users in a requested timeframe
Also, this creates a new endpoint `grouped` where you can pass a list of userIds with their billing cycle and retrieve their usage in a single query
> usage: query usage for recently active users

- views/bigquery.go
- views/bigquery_test.go
Before this PR, if BigQuery returns null in some of the columns, then a call to /data/views/query returns an error:
"bigquery error: error reading query result: bigquery: NULL cannot be assigned to field `PlaytimeMins` of type float64"
After this change, it will return the following:
```
[
{
"viewCount": 0,
"playtimeMins": 0,
"ttffMs": 0,
"rebufferRatio": 0,
"errorRate": 0,
"exitsBeforeStart": 0
}
]
```
Related to https://linear.app/livepeer/issue/PS-191/grafana-engagement-data-issues, though it does no solve the root cause of that issue.
> Fix BigQuery select with null values

- api/handler.go
- health/core.go
- health/record.go
- health/reducer.go
- health/reducers/stream_state.go
This is to create an API that blocks until a given stream has started. This is required in the
integration of a customer which requires the Create Stream API to block until the given stream
is started (for a pull-ingest stream).
The idea is that the Studio API will call the analyzer service when the blocking behavior is desired
and indirectly block the Create Stream API itself.
> health: Create API to wait for a stream to become active

- usage/bigquery.go
creator_id_type doesn't exist on usage table only viewership
> api/usage: Fix query by creatorId

- api/authorization.go
- api/handler.go
- cmd/analyzer/analyzer.go
- usage/bigquery.go
- usage/client.go
- usage/query_spec.go
- views/bigquery.go
- views/client.go
- views/query_spec.go
* added the ability to breakdown by creator id to the usage metrics api
* Added nullable types to remove unused grouping fields (time interval, creator id). 
* Fixed UsageWithTimestamp that did not return the time interval
* increased default query quota that consistently failed
Test Queries
I used Trovo's api key
```
import requests
url = 'http://127.0.0.1:8080/data/usage/query'
headers={'Authorization': 'Bearer ' + key}
params = {
'from': int(time.mktime((datetime.utcnow() - timedelta(days=1)).timetuple()))*1000,
'to': int(time.mktime(datetime.utcnow().timetuple()))*1000,
}
params = {
'from': int(time.mktime((datetime.utcnow() - timedelta(days=1)).timetuple()))*1000,
'to': int(time.mktime(datetime.utcnow().timetuple()))*1000,
'breakdownBy[]':['creatorId' ], 
}
params = {
'from': …
```
> Usage API: breakdownBy=creatorId

- api/handler.go
- views/clickhouse.go
- views/client.go
- views/client_test.go
As discussed in [Discord](https://discord.com/channels/423160867534929930/1217483431114706974/1217483433303867422), we split `/data/views/active` API into two separate APIs:
- `/data/views/now`
- `/data/views/internal/timeSeries`
fix https://linear.app/livepeer/issue/ENG-1799/revisit-viewsactive-api
> Split Realtime Viewership API into Now and Time Series APIs

- api/authorization.go
- api/handler.go
- go.mod
- go.sum
- views/clickhouse.go
- views/client.go
- views/query_spec.go
With merging this PR we need to wait for the following parts:
- @ecmulli to implement Clickpipes / SQL changes
- @gioelecerati to implement `projectId` in `/api/auth`
- @gioelecerati to fix returning `projectId` while listing assets/streams (also with admin token key)
fix https://linear.app/livepeer/issue/ENG-1980/add-filtering-by-projectid-in-livepeer-data
> Add projectId to /data/queries

- api/authorization.go
- api/handler.go
- go.mod
- go.sum
- views/clickhouse.go
- views/client.go
- views/query_spec.go
This reverts commit 30c2354466d47fdc808c35457efeda50be0e4684.
> Reapply "Add projectId to /data/queries (#190)""

- api/authorization.go
Currently, when a user passes a not-existing stream, asset, or playback, we print this weird message to the user:
```json
{
"errors": [
"failed to find object from x-livepeer-playback-id header"
]
}
```
I don't think we should print it, it's meaningless to users. They don't even pass this `x-livepeer-playback-id` header.
fix https://linear.app/livepeer/issue/ENG-2094/fix-filtering-by-non-existing-playbackid
> Improve user-facing error message

- api/handler.go
- views/client.go
- views/prometheus.go
Related to https://www.notion.so/livepeer/Cap-50k-Fishtank-viewers-a828ef8d037a4f27b9a6769d91c50b23
> Add endpoint /views/internal/server/now

- views/client.go
- Checking against stream.ProjectId instead of stream.UserID
> data: views: fix streams by project filter

- prometheus/prometheus.go
Ignore secodary AI nodes, these are only in staging but they don't form part of the regular pool of Os.
> Ignore secondary nodes

- ai/client.go
- api/handler.go
- prometheus/prometheus.go
- 1legion nodes are still reporting capacity so we need to ignore.
- Improve filtering to allow more flexibility in including/excluding regions with queryparams.
> Improve filtering and ignore 1legion

- ai/client.go
- cmd/analyzer/analyzer.go
- prometheus/prometheus.go
I'll use this to switch between the existing O reported metrics and the new Gateway ones by adding a filter to check for the existence of a tag only reported by the Gateway.
> Support for adding additional capacity filters in config

- prometheus/prometheus.go
We need this for the load tests to determine whether we have enough streams running.
> Return number of active AI streams
